name: Publish NPM Package

on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: cd npm && npm install
      - run: cd npm && npm run build
      - run: cd npm && npm test
      - run: cd npm && npm publish
